name: Build and Deploy Go Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Go application
      run: |
        go mod tidy
        go build -o hello-botgague ./...

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: docker build . -t venkatesh9722/hello-botgague:${{ github.sha }}

    - name: Push Docker image
      run: docker push venkatesh9722/hello-botgague:${{ github.sha }}
